<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub to slug channel not id which is the default
    }

    public function threads()
    {
        return $this->hasMany(Thread::class);
    }
}
